name: random_user
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  build_runner: ^2.3.2
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  get_it: ^7.2.0
  http: ^0.13.5
  http_parser: ^4.0.2
  json_annotation: ^4.7.0
  json_serializable: ^6.5.4
  shared_preferences: ^2.0.15
  slidy: ^4.0.3
  stacked: ^3.0.0
  stacked_hooks: ^0.2.2

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/
